services:
  phack-api:
    build: .
    container_name: phack-api
    expose:
      - "3000"
    environment:
      - TZ=America/Indiana/Indianapolis

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - phack-api
